### TEST Get / Website
GET http://localhost:8003

### Test Get / Homepage
GET http://localhost:8003/home

### Test DATA Endpoint
GET http://localhost:8003/api/data

### Test HTML + DATA in Template literal format:
GET http://localhost:8003/html

### Data endpoint of adding user - POST request:
POST http://localhost:8003/html
Content-Type: application/json

{
    "name": "Rada",
    "greet": "Jello"
}

### DATA TO DELETE WILL BE Deleted from this endpoint:
DELETE http://localhost:8003/html